### ISSUE TITLE
What is the parameter for GET_SENSOR_INFO ?

### ISSUE THREAD

**Issue by murkle** [VernierST/godirect-js#1005]
Please can you tell me what the parameter to command 0x50 is?

```
const GET_SENSOR_INFO = new Uint8Array([0x50, 0x00]);
```

It seems to be 1 for the Go Direct Temperature device

**Comment by stocktonkincade** [comment]
That is the channel number you are querying for info. I believe the command fails for channels that are not enabled, so one could simply loop through the integers from 0 to 31 to get all channel info. You can also get the enabled channels using the GET_SENSOR_IDS command. See: [_getAvailableSensors](https://github.com/VernierST/godirect-js/blob/main/src/Device.js#LL427C33-L427C33)
