### ISSUE TITLE
NUMERIC_MEAS_TYPE and SAMPLING_MODE are pulled from wrong offest

### ISSUE THREAD

**Issue by stocktonkincade** [VernierST/godirect-js#29]
When requesting GET_SENSOR_INFO, the NUMERIC_MEAS_TYPE (type) and SAMPLING_MODE (mode) are being parsed from the wrong offset in the buffer. These should be 6 and 7, respectively.

**Comment by jordanaustin** [comment]
Inadvertently closed by a PR
