### ISSUE TITLE
change the measurementPeriod

### ISSUE THREAD

**Issue by mklewandowski** [VernierST/godirect-js#44]
Is the Javascript library designed to allow the device `measurementPeriod` to be changed?  Many of our sensors have a default period of 500 milliseconds, but we would like to change that number. 
 `Device.js` contains a `_setMeasurementPeriod` function, but based on its underscore naming convention, it is clearly designed to be a private method and not used externally.  Is there a way to change `measurementPeriod` in the current implementation or is this a feature that might eventually be added?

**Comment by stocktonkincade** [comment]
The measurement period of a Vernier Go Direct device really only matters during an active collection. So, partly to simplify the API, we set the measurement period only through the ```Device.start``` function. This will indirectly call the ```_setMeasurementPeriod``` function through the private ```_startMeasurements``` function. We may add a direct accessor to the measurement period in the future, but the current model seems to suffice for most cases.

**Comment by mklewandowski** [comment]
Got it!  That all makes sense.  Thanks so much!
