### ISSUE TITLE
Sensor calibration

### ISSUE THREAD

**Issue by mstllc** [VernierST/godirect-js#440]
Hi!  Thanks so much for sharing this library, it's very helpful!

I was wondering if you have any plans to expose methods for the various GDX devices that allow for calibrating the sensors?  Currently there are a number of devices that allow for sensor calibration through Graphical Analysis (force cart, etc).  Would you consider exposing methods to do those calibrations through this Javscript library?

Thanks again for your work here, let me know if you have questions or if I can help!

**Comment by minorgal** [comment]
At this time we don't have any plans to add this functionality.

**Comment by mstllc** [comment]
Ok, thanks so much for the update!
