### ISSUE TITLE
Measurement Rate at 50ms

### ISSUE THREAD

**Issue by louistb** [VernierST/godirect-js#523]
Hi,

I did a quick support chat on the website and i was told to open a git issues for this.

Just to give a quick context, I ordered a Go direct respiration belt to be used in an interactive installation. The installation is an interactive breathing exercise. It uses node js to connect to the sensor and Unity to render the visual and to handle the game logic.

I was able to adapt your javascript library to be used with node js and with no human interaction for connection and reconnecting, it's been working like a charm. 

One of the things I wanted to get more info on is the measurement period. From the specs and the documentation I understand that the minimum period is 50ms, but even when setting the sensor to use a 50ms period, it seems like I'm getting an average of 80ms delta between data packets.

i'm using the start method param to pass the wanted measurement in ms (50 in that case) the resulting bytes sent are (in hex format) :

1bff0050c3000000000000

Let me know if I should expect a steady 50 ms and if I'm missing anything on the setup.

I can still filter the data and it's very usable but I'm really trying to get the most realtime reading possible.

Thanks a lot for your time

**Comment by dvernier** [comment]
Hello,

I will make a few comments and also I am copying a couple other people who
might have some suggestions. If they have suggestions, they are welcome to
send them to you.

First of all, have you experimented with this sensor using our Graphical
Analysis program? If you do, you will see that Graphical Analysis offers
you 4 channels that it can read.

Now, from a "do-it-yourself" programmer point of view, the one to use is
just Force. Essentially, the sensor will read force and you can tell it how
often to read that force. Then, it is up to you do do what you want with
the force measurements. You can graph them, figure out rates from them, or
whatever else you want to do.

I do not know how you use the other channels. In Python, and I think in our
Arduino programs, the rate channel is returned as "nan" not a number. That
probably happens in Javascript also. I do not know. These channels have the
GDX hardware do some calculations and then periodically report rates. I do
not think we document how this is all done.

Dave

David L. Vernier
Founder and Co-President
Vernier Software & Technology
13979 SW Millikan Way
Beaverton, OR  97005
503-277-2299
1-888-Vernier (1-888-837-6437)
***@***.***
www.vernier.com

**Comment by louistb** [comment]
Hi, thanks for the response.

Yea i am using the force and its been working super good.

My question would be simply : 

What is the best refresh rate i should expect from the sensor ? 

I currently have an average of +/- 80ms between messages

Documentation says the sensor has a 50ms response time, should i be able to get a steady 50ms ? 

Thanks

**Comment by dvernier** [comment]
Hello again,

>>What is the best refresh rate i should expect from the sensor ?

I guess I do not understand what you mean by "refresh rate". You can read
the Force as fast as you want, dozens of times a second, or slow. It is
totally up to you. The force sensor response is very fast. Now do you mean
"how often should I do the math to figure out a rate?"

>>Documentation says the sensor has a 50ms response time, should i be able
to get a steady 50ms ?

I do not know how we came up with the figure of 50ms as a response time.

Dave
David L. Vernier
Founder and Co-President
Vernier Software & Technology
13979 SW Millikan Way
Beaverton, OR  97005
503-277-2299
1-888-Vernier (1-888-837-6437)
***@***.***
www.vernier.com

**Comment by louistb** [comment]
HI Dave thanks for your fast responses,

So considering i am working on a interactive installation and that data is used Realtime, i am trying to get the most data i can per second.  So the node js program i wrote just grabs the raw data and normalizes it to 0-1. All the logic on respiration data is done in another program (they both communicate in web sockets).

If i start the sensor with a requested measurement rate of 50ms ( i ask the sensor to return me the data at 50ms ) , i dont get this rate from the sensor, the sensor only sends me data on a interval of around 80ms.

Here is where i found the 50ms mention : 

![image](https://user-images.githubusercontent.com/2654241/122096887-075e0200-cddd-11eb-919e-52b1f3ad5036.png)

Thanks again

**Comment by dvernier** [comment]
OK. I think this is all about Javascript and how it responds. With Python
or Arduino, I can read the force from the GDX-RB dozens of times a second,
maybe hundreds of times a second.

I will ask a guy here to try Javascript with the GDX-RB.

Dave
David L. Vernier
Founder and Co-President
Vernier Software & Technology
13979 SW Millikan Way
Beaverton, OR  97005
503-277-2299
1-888-Vernier (1-888-837-6437)
***@***.***
www.vernier.com

**Comment by stocktonkincade** [comment]
The response time listed there refers to the physical response time of the internal strain gauge. That is, the hardware is capable of detecting force measurements every 50 ms. This is the fastest supported rate that the device provides meaningful force data. Under optimal communications conditions, one should be able to gather force measurements from the GDX device at that interval. In fact, our Graphical Analysis software is capable of collecting data from this device at 200 Hz. Note that the Graphical Analysis application does not use the godirect-js module (webBluetooth), but a native hardware/system communication stack.
I believe that you may be running into a performance limitation of the godirect-js stack. While you can instruct the device to sample at any given delta through the gdxdevice.start() function, it will only go as fast as it is allowed. In the case of the RB, it will be 50 ms (200 Hz). While the device itself will be collecting samples internally at that rate, there can be an inherent latency on the host side as it is attempting to stream the data in real time. The device will buffer the measurements to some degree, knowing that the host is trying to stream them and may have some realtime constraints. In my quick experiments using [this little web app](https://glitch.com/edit/#!/green-diligent-oval?path=index.html%3A193%3A58), I see that the host is really only able to keep up with about 100 Hz over BLE. It is a little more performant over USB, but not much. Even at 100Hz, my application begins to degrade after a few hundred samples are collected.

**Comment by louistb** [comment]
> The response time listed there refers to the physical response time of the internal strain gauge. That is, the hardware is capable of detecting force measurements every 50 ms. This is the fastest supported rate that the device provides meaningful force data. Under optimal communications conditions, one should be able to gather force measurements from the GDX device at that interval. In fact, our Graphical Analysis software is capable of collecting data from this device at 200 Hz. Note that the Graphical Analysis application does not use the godirect-js module (webBluetooth), but a native hardware/system communication stack.
> I believe that you may be running into a performance limitation of the godirect-js stack. While you can instruct the device to sample at any given delta through the gdxdevice.start() function, it will only go as fast as it is allowed. In the case of the RB, it will be 50 ms (200 Hz). While the device itself will be collecting samples internally at that rate, there can be an inherent latency on the host side as it is attempting to stream the data in real time. The device will buffer the measurements to some degree, knowing that the host is trying to stream them and may have some realtime constraints. In my quick experiments using [this little web app](https://glitch.com/edit/#!/green-diligent-oval?path=index.html%3A193%3A58), I see that the host is really only able to keep up with about 100 Hz over BLE. It is a little more performant over USB, but not much. Even at 100Hz, my application begins to degrade after a few hundred samples are collected.

Thanks for all of these infos, it tried to setup a python project and im getting very similar results, like you said it seems like it gets stuck after a certain amough of packets then starts back at full speed. So it feels like a hardware limitation.

Thanks a lot for you help.

I will play around to see if i can get a more steady flow of packet by playing around with mesurement rates.
